package com.example.data

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String, val flag: String) {
    ENGLISH("en", "English", "English", "🇺🇸"),
    SPANISH("es", "Spanish", "Español", "🇪🇸"),
    FRENCH("fr", "French", "Français", "🇫🇷"),
    ARABIC("ar", "Arabic", "العربية", "🇸🇦"),
    PORTUGUESE("pt", "Portuguese", "Português", "🇧🇷"),
    CHINESE("zh", "Chinese", "中文", "🇨🇳"),
    RUSSIAN("ru", "Russian", "Русский", "🇷🇺"),
    INDONESIAN("id", "Indonesian", "Bahasa Indonesia", "🇮🇩")
}

object LanguageManager {
    fun getString(key: String, language: AppLanguage): String {
        return translations[language]?.get(key) ?: translations[AppLanguage.ENGLISH]?.get(key) ?: key
    }

    private val translations: Map<AppLanguage, Map<String, String>> = mapOf(
        AppLanguage.ENGLISH to mapOf(
            "app_title" to "AdEarn",
            "tagline" to "Watch Rewarded Ads & Earn USDT",
            "dashboard" to "Dashboard",
            "watch_ads" to "Watch Ads",
            "vip_packages" to "VIP Packages",
            "wallet" to "Wallet",
            "notifications" to "Notifications",
            "daily_ad_limit" to "Daily Ad Limit",
            "ads_watched_today" to "Ads Watched Today",
            "remaining_today" to "Remaining Today",
            "resets_in" to "Resets in",
            "total_balance" to "Total Balance",
            "today_earnings" to "Today's Earnings",
            "all_time_earnings" to "All-Time Earnings",
            "vip_status" to "VIP Status",
            "multiplier" to "Multiplier",
            "upgrade_vip" to "Upgrade VIP",
            "current_plan" to "Current Plan",
            "withdrawal_eligibility" to "Withdrawal Eligibility",
            "withdrawal_locked" to "Withdrawal Locked",
            "withdrawal_unlocked" to "Eligible for Payout",
            "min_threshold_info" to "Minimum withdrawal threshold is $50.00 USDT.",
            "need_more_to_withdraw" to "Earn %s more to unlock withdrawal.",
            "ready_to_withdraw" to "You have reached the $50 minimum threshold!",
            "withdraw_now" to "Withdraw Now",
            "deposit_funds" to "Deposit Funds",
            "recent_transactions" to "Recent Transactions",
            "view_all" to "View All",
            "duration" to "Duration",
            "reward" to "Reward",
            "watch_and_earn" to "Watch & Earn",
            "daily_limit_reached" to "Daily Limit Reached",
            "daily_limit_reached_desc" to "You have watched all your daily ads. Upgrade your VIP tier to watch up to 40 ads daily!",
            "ad_player_title" to "Sponsored Rewarded Ad",
            "ad_verifying" to "Verifying completion...",
            "ad_seconds_remaining" to "seconds remaining",
            "claim_reward" to "Claim Reward",
            "cannot_skip" to "Please watch the full ad to receive your reward",
            "reward_earned_title" to "Reward Claimed!",
            "reward_earned_desc" to "Successfully credited %s to your wallet.",
            "admin_trc20_address" to "Official Admin USDT TRC20 Address",
            "copy_address" to "Copy Address",
            "address_copied" to "USDT TRC20 Address copied to clipboard!",
            "network_notice" to "Network: TRC20 only. Deposits sent via other networks will be lost.",
            "submit_deposit" to "Submit Deposit Proof",
            "tx_hash" to "Transaction Hash (TxID)",
            "tx_hash_hint" to "Paste 64-character TRC20 TxID",
            "deposit_amount" to "Deposit Amount (USDT)",
            "confirm_deposit" to "Verify & Activate",
            "withdraw_usdt" to "Withdraw USDT (TRC20)",
            "recipient_address" to "Recipient TRC20 Address",
            "recipient_hint" to "Enter your TRC20 address (Starts with T)",
            "withdraw_amount" to "Withdrawal Amount ($)",
            "min_withdrawal_error" to "Minimum withdrawal amount is $50.00",
            "insufficient_balance" to "Insufficient balance",
            "invalid_trc20" to "Invalid TRC20 address. Must start with 'T' and be 34 characters.",
            "withdraw_submitted" to "Withdrawal request submitted for review.",
            "tier_free" to "Free Member",
            "tier_bronze" to "VIP 1 (Bronze)",
            "tier_silver" to "VIP 2 (Silver)",
            "tier_gold" to "VIP 3 (Gold)",
            "tier_diamond" to "VIP 4 (Diamond)",
            "daily_ads_count" to "%d Daily Ads",
            "boost_info" to "%.2fx Earnings Multiplier",
            "pay_with_balance" to "Pay from Balance",
            "pay_with_usdt" to "Pay via USDT TRC20",
            "status_completed" to "Completed",
            "status_pending" to "Pending Review",
            "status_processing" to "Processing",
            "filter_all" to "All",
            "filter_rewards" to "Ad Rewards",
            "filter_vip" to "VIP Upgrades",
            "filter_withdrawals" to "Withdrawals",
            "filter_deposits" to "Deposits",
            "select_language" to "Select Language",
            "no_transactions" to "No transactions found yet.",
            "ad_rule_notice" to "Earning rate: 10s = $0.10, 20s = $0.20 (strictly capped under $0.50 per ad)."
        ),
        AppLanguage.SPANISH to mapOf(
            "app_title" to "AdEarn",
            "tagline" to "Mira anuncios y gana USDT",
            "dashboard" to "Panel",
            "watch_ads" to "Ver Anuncios",
            "vip_packages" to "Paquetes VIP",
            "wallet" to "Billetera",
            "notifications" to "Notificaciones",
            "daily_ad_limit" to "Límite Diario de Anuncios",
            "ads_watched_today" to "Anuncios Vistos Hoy",
            "remaining_today" to "Restantes Hoy",
            "resets_in" to "Se reinicia en",
            "total_balance" to "Saldo Total",
            "today_earnings" to "Ganancias de Hoy",
            "all_time_earnings" to "Ganancias Totales",
            "vip_status" to "Estado VIP",
            "multiplier" to "Multiplicador",
            "upgrade_vip" to "Mejorar VIP",
            "current_plan" to "Plan Actual",
            "withdrawal_eligibility" to "Elegibilidad de Retiro",
            "withdrawal_locked" to "Retiro Bloqueado",
            "withdrawal_unlocked" to "Elegible para Retiro",
            "min_threshold_info" to "El retiro mínimo es de $50.00 USDT.",
            "need_more_to_withdraw" to "Gana %s más para desbloquear retiros.",
            "ready_to_withdraw" to "¡Has alcanzado el umbral de $50!",
            "withdraw_now" to "Retirar Ahora",
            "deposit_funds" to "Depositar Fondos",
            "recent_transactions" to "Transacciones Recientes",
            "view_all" to "Ver Todo",
            "duration" to "Duración",
            "reward" to "Recompensa",
            "watch_and_earn" to "Ver y Ganar",
            "daily_limit_reached" to "Límite Diario Alcanzado",
            "daily_limit_reached_desc" to "Has visto todos los anuncios de hoy. ¡Mejora tu VIP para ver hasta 40 anuncios diarios!",
            "ad_player_title" to "Anuncio Recompensado",
            "ad_verifying" to "Verificando...",
            "ad_seconds_remaining" to "segundos restantes",
            "claim_reward" to "Reclamar Recompensa",
            "cannot_skip" to "Mira el anuncio completo para recibir tu pago",
            "reward_earned_title" to "¡Recompensa Reclamada!",
            "reward_earned_desc" to "Se acreditaron %s en tu billetera.",
            "admin_trc20_address" to "Dirección Oficial USDT TRC20 del Administrador",
            "copy_address" to "Copiar Dirección",
            "address_copied" to "¡Dirección copiada al portapapeles!",
            "network_notice" to "Red: Solo TRC20.",
            "submit_deposit" to "Enviar Comprobante de Depósito",
            "tx_hash" to "Hash de Transacción (TxID)",
            "tx_hash_hint" to "Pega el TxID TRC20",
            "deposit_amount" to "Monto del Depósito (USDT)",
            "confirm_deposit" to "Verificar y Activar",
            "withdraw_usdt" to "Retirar USDT (TRC20)",
            "recipient_address" to "Dirección TRC20 del Destinatario",
            "recipient_hint" to "Empieza con T (34 caracteres)",
            "withdraw_amount" to "Monto a Retirar ($)",
            "min_withdrawal_error" to "El retiro mínimo es $50.00",
            "insufficient_balance" to "Saldo insuficiente",
            "invalid_trc20" to "Dirección TRC20 inválida.",
            "withdraw_submitted" to "Solicitud de retiro enviada.",
            "tier_free" to "Miembro Gratis",
            "tier_bronze" to "VIP 1 (Bronce)",
            "tier_silver" to "VIP 2 (Plata)",
            "tier_gold" to "VIP 3 (Oro)",
            "tier_diamond" to "VIP 4 (Diamante)",
            "daily_ads_count" to "%d Anuncios Diarios",
            "boost_info" to "Multiplicador de %.2fx",
            "pay_with_balance" to "Pagar con Saldo",
            "pay_with_usdt" to "Pagar con USDT TRC20",
            "status_completed" to "Completado",
            "status_pending" to "Pendiente",
            "status_processing" to "En Proceso",
            "filter_all" to "Todos",
            "filter_rewards" to "Recompensas",
            "filter_vip" to "Mejoras VIP",
            "filter_withdrawals" to "Retiros",
            "filter_deposits" to "Depósitos",
            "select_language" to "Seleccionar Idioma",
            "no_transactions" to "No hay transacciones aún.",
            "ad_rule_notice" to "Pago: 10s = $0.10, 20s = $0.20 (límite estricto < $0.50 por anuncio)."
        ),
        AppLanguage.FRENCH to mapOf(
            "app_title" to "AdEarn",
            "tagline" to "Regardez des pubs et gagnez des USDT",
            "dashboard" to "Tableau de Bord",
            "watch_ads" to "Voir Pubs",
            "vip_packages" to "Packs VIP",
            "wallet" to "Portefeuille",
            "notifications" to "Notifications",
            "daily_ad_limit" to "Limite Quotidienne",
            "ads_watched_today" to "Pubs Vues Aujourd'hui",
            "remaining_today" to "Restantes Aujourd'hui",
            "resets_in" to "Réinitialisation dans",
            "total_balance" to "Solde Total",
            "today_earnings" to "Gains du Jour",
            "all_time_earnings" to "Gains Totaux",
            "vip_status" to "Statut VIP",
            "multiplier" to "Multiplicateur",
            "upgrade_vip" to "Améliorer VIP",
            "withdrawal_eligibility" to "Éligibilité au Retrait",
            "withdrawal_locked" to "Retrait Bloqué",
            "withdrawal_unlocked" to "Éligible au Retrait",
            "min_threshold_info" to "Le seuil minimum de retrait est de 50,00 $ USDT.",
            "need_more_to_withdraw" to "Gagnez %s de plus pour débloquer.",
            "ready_to_withdraw" to "Seuil de 50 $ atteint !",
            "withdraw_now" to "Retirer",
            "deposit_funds" to "Déposer",
            "recent_transactions" to "Transactions Récentes",
            "view_all" to "Voir Tout",
            "admin_trc20_address" to "Adresse Officielle USDT TRC20 Admin",
            "copy_address" to "Copier l'Adresse",
            "address_copied" to "Adresse copiée !",
            "network_notice" to "Réseau : TRC20 uniquement.",
            "claim_reward" to "Réclamer",
            "ad_rule_notice" to "Tarif : 10s = 0,10 $, 20s = 0,20 $ (plafonné à < 0,50 $)."
        ),
        AppLanguage.ARABIC to mapOf(
            "app_title" to "AdEarn",
            "tagline" to "شاهد الإعلانات واربح USDT",
            "dashboard" to "لوحة التحكم",
            "watch_ads" to "مشاهدة الإعلانات",
            "vip_packages" to "باقات VIP",
            "wallet" to "المحفظة",
            "notifications" to "الإشعارات",
            "daily_ad_limit" to "الحد اليومي للإعلانات",
            "ads_watched_today" to "الإعلانات المشاهدة اليوم",
            "remaining_today" to "المتبقي اليوم",
            "total_balance" to "الرصيد الإجمالي",
            "today_earnings" to "أرباح اليوم",
            "all_time_earnings" to "إجمالي الأرباح",
            "vip_status" to "حالة VIP",
            "upgrade_vip" to "ترقية VIP",
            "withdrawal_eligibility" to "أهلية السحب",
            "withdrawal_locked" to "السحب مقفل",
            "withdrawal_unlocked" to "مؤهل للسحب",
            "min_threshold_info" to "الحد الأدنى للسحب هو 50.00 دولار USDT.",
            "withdraw_now" to "سحب الآن",
            "deposit_funds" to "إيداع",
            "admin_trc20_address" to "عنوان USDT TRC20 الرسمي للإدارة",
            "copy_address" to "نسخ العنوان",
            "claim_reward" to "استلام المكافأة",
            "ad_rule_notice" to "الأرباح: 10ث = $0.10، 20ث = $0.20 (الحد الأقصى أقل من $0.50)."
        ),
        AppLanguage.CHINESE to mapOf(
            "app_title" to "AdEarn",
            "tagline" to "观看激励广告赚取 USDT",
            "dashboard" to "控制台",
            "watch_ads" to "看广告赚钱",
            "vip_packages" to "VIP 会员套餐",
            "wallet" to "钱包中心",
            "notifications" to "消息通知",
            "daily_ad_limit" to "每日广告上限",
            "ads_watched_today" to "今日已看广告",
            "remaining_today" to "今日剩余次数",
            "total_balance" to "钱包总余额",
            "today_earnings" to "今日累计收益",
            "all_time_earnings" to "历史总收益",
            "vip_status" to "当前 VIP 等级",
            "upgrade_vip" to "升级 VIP 会员",
            "withdrawal_eligibility" to "提现资格状态",
            "withdrawal_locked" to "提现未解锁 (最低 $50)",
            "withdrawal_unlocked" to "已达提现标准",
            "min_threshold_info" to "最低提现门槛为 50.00 USDT。",
            "withdraw_now" to "立即申请提现",
            "deposit_funds" to "充值入金",
            "admin_trc20_address" to "官方管理员 USDT TRC20 地址",
            "copy_address" to "复制地址",
            "claim_reward" to "领取奖励",
            "ad_rule_notice" to "收益规则：10秒 = $0.10，20秒 = $0.20（每条严格限制在 $0.50 以下）。"
        ),
        AppLanguage.PORTUGUESE to mapOf(
            "app_title" to "AdEarn",
            "tagline" to "Assista a anúncios e ganhe USDT",
            "dashboard" to "Painel",
            "watch_ads" to "Ver Anúncios",
            "vip_packages" to "Pacotes VIP",
            "wallet" to "Carteira",
            "notifications" to "Notificações",
            "daily_ad_limit" to "Limite Diário",
            "ads_watched_today" to "Assistidos Hoje",
            "remaining_today" to "Restantes Hoje",
            "total_balance" to "Saldo Total",
            "today_earnings" to "Ganhos de Hoje",
            "all_time_earnings" to "Ganhos Totais",
            "vip_status" to "Status VIP",
            "upgrade_vip" to "Atualizar VIP",
            "withdrawal_eligibility" to "Elegibilidade de Saque",
            "withdrawal_locked" to "Saque Bloqueado",
            "withdrawal_unlocked" to "Elegível para Saque",
            "min_threshold_info" to "O limite mínimo de saque é de $50,00 USDT.",
            "withdraw_now" to "Sacar Agora",
            "deposit_funds" to "Depositar",
            "admin_trc20_address" to "Endereço Oficial USDT TRC20 do Admin",
            "copy_address" to "Copiar Endereço",
            "claim_reward" to "Resgatar Recompensa",
            "ad_rule_notice" to "Ganhos: 10s = $0,10, 20s = $0,20 (estritamente limitado a < $0,50)."
        ),
        AppLanguage.RUSSIAN to mapOf(
            "app_title" to "AdEarn",
            "tagline" to "Смотрите рекламу и зарабатывайте USDT",
            "dashboard" to "Панель",
            "watch_ads" to "Просмотр",
            "vip_packages" to "VIP Пакеты",
            "wallet" to "Кошелек",
            "notifications" to "Уведомления",
            "daily_ad_limit" to "Дневной лимит",
            "ads_watched_today" to "Просмотрено сегодня",
            "remaining_today" to "Осталось сегодня",
            "total_balance" to "Общий баланс",
            "today_earnings" to "Доход сегодня",
            "all_time_earnings" to "Всего заработано",
            "vip_status" to "VIP статус",
            "upgrade_vip" to "Улучшить VIP",
            "withdrawal_eligibility" to "Статус вывода",
            "withdrawal_locked" to "Вывод заблокирован",
            "withdrawal_unlocked" to "Доступен вывод",
            "min_threshold_info" to "Минимальная сумма вывода составляет $50.00 USDT.",
            "withdraw_now" to "Вывести средства",
            "deposit_funds" to "Пополнить баланс",
            "admin_trc20_address" to "Официальный USDT TRC20 адрес админа",
            "copy_address" to "Скопировать адрес",
            "claim_reward" to "Забрать награду",
            "ad_rule_notice" to "Тариф: 10с = $0.10, 20с = $0.20 (строго до $0.50 за рекламу)."
        ),
        AppLanguage.INDONESIAN to mapOf(
            "app_title" to "AdEarn",
            "tagline" to "Tonton Iklan & Dapatkan USDT",
            "dashboard" to "Dasbor",
            "watch_ads" to "Tonton Iklan",
            "vip_packages" to "Paket VIP",
            "wallet" to "Dompet",
            "notifications" to "Notifikasi",
            "daily_ad_limit" to "Batas Iklan Harian",
            "ads_watched_today" to "Iklan Ditonton Hari Ini",
            "remaining_today" to "Sisa Hari Ini",
            "total_balance" to "Total Saldo",
            "today_earnings" to "Penghasilan Hari Ini",
            "all_time_earnings" to "Total Penghasilan",
            "vip_status" to "Status VIP",
            "upgrade_vip" to "Tingkatkan VIP",
            "withdrawal_eligibility" to "Kelayakan Penarikan",
            "withdrawal_locked" to "Penarikan Terkunci",
            "withdrawal_unlocked" to "Siap untuk Penarikan",
            "min_threshold_info" to "Batas minimum penarikan adalah $50.00 USDT.",
            "withdraw_now" to "Tarik Sekarang",
            "deposit_funds" to "Setor Dana",
            "admin_trc20_address" to "Alamat Resmi USDT TRC20 Admin",
            "copy_address" to "Salin Alamat",
            "claim_reward" to "Klaim Hadiah",
            "ad_rule_notice" to "Tarif: 10d = $0.10, 20d = $0.20 (dibatasi ketat di bawah $0.50)."
        )
    )
}
